### ISSUE TITLE
Separate build and project pages TODO

### ISSUE THREAD

**Issue by chrismeyers** [chrismeyers/chrismeyers.info#27]
- [X] Scale title in header
- [x] Fix command prompt `cd` to individual build/project
- [x] Return to `scrollBehavior`'s `savedPosition` on mobile - currently resets to 0, 0
- [x] General mobile styling/usability QA

**Comment by chrismeyers** [comment]
Changing between portrait to landscape and back on iOS Chrome causes the width of the content to shrink when returning to portrait.  The tab needs to be reloaded or the address bar needs to be resubmitted to get back to normal (refresh doesn't fix it).  This is happening on other websites, so it's likely a problem with the browser.
